---
server:
  port: '${PORT:${SERVER_PORT:0}}'

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball
